### PR TITLE
Conform types to hashable and identifiable

### PR DESCRIPTION
**Pull request by creekdrops**
This PR applies the Hashable and Identifiable protocols to all applicable structs. This will allow for easier iteration when looping over data since Hashable allows the user to utilize `id: \.self` when iterating.

**Change log:**
- Identifiable stucts (i.e. stucts that contain an id property) conform to both identifiable and hashable.
- All 'View" structs now conform to hashable.
- Non-identifiable structs conform to hashable.

### CODE REVIEW

**Comment by fishcharlie** [comment]
@creekdrops Sorry for so many merge conflicts. But is there any chance you could take a look at those?

**Comment by creekdrops** [comment]
Yeah, I'll work on cleaning them up.

**Comment by creekdrops** [comment]
@fishcharlie merge conflicts should now be resolved with the changes you made earlier.

**Review by fishcharlie — APPROVED** [review]
Thanks for the contribution!

**Comment by RezMePlease** [comment]
BLESS

**Pull request merged**
