### PR TITLE
Date fixes, intValue methods, error handling

### PR DESCRIPTION
**Pull request by mdhiggins**
Made a few additional improvements to the API that I wanted to see if you were interested in merging back

I went through and changed the datatype for all the instances of `published` and `updated` to Date objects and added an ISO8061 date formatter to handle this translation. Lemmy appears to occasionally include the millisecond data and sometimes it doesn't which resulted in some errors, so that's the reason its implemented with both approaches

I also noticed that `SortType` and `ListingType` are strings everywhere except the user settings classes, which I confirmed is a weird inconsistent implementation on Lemmy's part as the types in their JS API are identical. Either way, I added some quick methods and initializers to convert between Integers and that type as well

Finally, I added some custom errors and some additional checks to the API calls. Lemmy doesn't seem to return an HTTP status code when successful but does if there are errors. I added some checks for when this happen and throw the status code and request data. I also added a throw that catches the decode errors as the data data returned often contained some message about why something failed which can be useful but would have otherwise been lost

### CODE REVIEW

**Comment by fishcharlie** [comment]
@mdhiggins Thanks for all your contributions! One thing I noticed. I have my settings set to tabs instead of spaces. I think it's important to keep things consistent.

This is my first Swift package, and I'm not aware of any tooling to easily enforce the indentation style of this project.

Do you happen to know of any system for that? I'm not completely opposed to switching the entire project to be spaces instead of tabs, but I do want it to be consistent, and probably in a different PR. Ideally we should also enforce it through some type of lint system.

Do you have any thoughts/advice on this?

**Comment by mdhiggins** [comment]
Looks like some of these changes have been undone in 0.18 which just went live on Lemmy.ml

New update broke the API so I included some of my fixes which got things working again for me, probably many more I haven't encountered

They fixed SortType/ListingType inconsistency

Also had a small fix with the dataFormatter included

With regards to your spacing, not sure offhand if there's an easy fix or way to enforce though I can try and be more aware for future pull requests

Edit: merged in latest changes to resolve conflicts and fixed the tab/space issue

**Comment by ckaik** [comment]
> This is my first Swift package, and I'm not aware of any tooling to easily enforce the indentation style of this project.
> 
> Do you happen to know of any system for that? I'm not completely opposed to switching the entire project to be spaces instead of tabs, but I do want it to be consistent, and probably in a different PR. Ideally we should also enforce it through some type of lint system.
> 
> Do you have any thoughts/advice on this?

Check out these:
* https://github.com/realm/SwiftLint
* https://github.com/nicklockwood/SwiftFormat

In my opinion I'd start with only one of the two, probably swiftformat.
There's also [swift-format](https://github.com/apple/swift-format) (great naming :|), and while it is an apple repo, I do prefer the "other" swiftformat over that one.

If you're interested I can have a look at it and create swiftlint and swiftformat configurations, then open a PR and you can see if you like it. Or just modify ist.

**Review by fishcharlie — CHANGES_REQUESTED** [review]
@mdhiggins I can't get this PR to work in my manual tests. Keep getting a compiler error in an area of my code that is completely unrelated.

This PR is also pretty massive which makes it incredibly difficult to narrow down what is going wrong. Not sure why Date fixes, intValue methods & error handling all need to be in 1 PR.

Please break this into separate PRs so it's easier to debug.

**Pull request closed without merging**
